
.PHONY: generated
generated: # Generating swiftgen
	@printf '\n\033[32m===== generate swiftgen files =====\033[0m\n'
	swiftgen

.PHONY: generate_keys
generate_keys: # Generating secure keys
	@printf '\n\033[32m===== generate keys =====\033[0m\n'
	sskeys generate
