# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Template' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for Template
  pod 'R.swift', '~> 6.1'
  pod 'SwiftEntryKit', '~> 2.0'
  pod 'Moya', '~> 15.0'
  pod 'SwiftLint'
  pod "DBDebugToolkit", :configurations => ['Develop', 'Staging']
  
end
